---
title: "day02_exercise"
author: "Tsun Fung Yau"
date: "7/21/2020"
output: pdf_document
---


 ========== 1. Have a look at the VSEM model description: ==========
library(BayesianTools)
?VSEM

```{r}
library(BayesianTools)
?VSEM
```
========== 2. Create some input data (radiation) and get a set of reference parameters as shown in the Examples section. ========== 
```{r}
PAR <- VSEMcreatePAR(1:1000)
plot(PAR, main = "PAR (driving the model)", xlab = "Day")

```

```{r}
# ========== 3. Get VSEM to run with the created data and visualize the simulated output (NEE and biomass pools). ========== 
#What catches your eye with regard to above- and below ground biomass, and how can you explain this?
# 1. Why is it possible for the pool values to be below zero?
# 2. The vlaues for above and below ground vegetation pool are in the same range. Above ground vegetation pool values are a bit more wide spread. 

# load reference parameter definition (upper, lower prior)
refPars <- VSEMgetDefaults()
# this adds one additional parameter for the likelihood standard deviation (see below)
refPars[12,] <- c(2, 0.1, 4) 
rownames(refPars)[12] <- "error-sd"
head(refPars)

# create some simulated test data 
# generally recommended to start with simulated data before moving to real data
referenceData <- VSEM(refPars$best[1:11], PAR) # model predictions with reference parameters  
referenceData[,1] = 1000 * referenceData[,1] 
# this adds the error - needs to conform to the error definition in the likelihood
obs <- referenceData + rnorm(length(referenceData), sd = refPars$best[12])
oldpar <- par(mfrow = c(2,2))
for (i in 1:4) plotTimeSeries(observed = obs[,i], 
                              predicted = referenceData[,i], main = colnames(referenceData)[i])
```

```{r}
# ========== 4. Start with the default parameterisation (which you can store in a matrix by calling VSEMgetDefaults()). ========== 
#Start with a single parameter and vary it from the default to the higher and lower extreme provided in VSEMgetDefaults(). 
#How much does your output change (e.g. absolute change in output / absolute change in parameter)? 
#And how about in %, as “elasticity” (i.e. % change in output / % change in parameter)? 
#Calculate both measures for the aboveground biomass output and the parameters LUE and tauV. 
#Do both parameters suggest comparable sensitivities?


```

```{r}
# ========== 5. Now visualise the sensitivity/model output for aboveground biomass of the first 6 parameters across their range of values (between lower and higher) for 20 steps. ========== 
#Only change one parameter at a time. What do you notice: are all parameter sensitivities linear?



```

```{r}
# ========== 6. Now do a Morris screening (function morris in package sensitivity), i.e. vary all 6 parameters together. ========== 
#Please note that though the first input of morris function in the sensitivity package is a function or a model, you can’t use VSEM directly. 
#The most convenient solution is to create a function (referred to as YourFun) that takes a matrix (e.g., mt) as first argument. 
#The matrix will contain the model parameters chosen (and changed) by the morris function in each row. 
#YourFun has to run VSEM with each parameter set contained in the rows of mt. 
#Be aware that your function will need to know which parameters in the reference parameter set have to be replaced by the mt row entries. 
#In this case, only the first 6 parameters of the reference parameter set will be altered by the morris function. 
#In addition, YourFun has to return a vector of VSEM results for e.g., above ground biomass (use the average).



```

```{r}
# ========== 7. Finally, we do a rough computer experiment: draw 1000 values uniformly from the range of each of the six parameters (Monte Carlo draw); compute for each combination the VSEM output. ========== 
#Now do a linear regression and analyse the standardized regression coefficients and correlation coefficients. 
#Plot both results: do they suggest the same sensitivities? Are they similar to the Morris screening?



```

